#include <algorithm>
#include <cstring>
#include <iostream>
#include <string>
#include <utility>

static char* duplicate(const char* text) {
	const std::size_t length = std::strlen(text) + 1;
	char* copy = new char[length];
	std::memcpy(copy, text, length);
	return copy;
}

// Type 1: a raw owning pointer plus compiler-generated copy means two owners of one buffer.
struct Broken {
	char* data;
	explicit Broken(const char* text) : data(duplicate(text)) {}
	~Broken() { delete[] data; } // BP: destructor exists, but copy/assignment were never declared.
};

void shallow_copy_double_free() {
#if defined(RUN_UNSAFE_EXAMPLE)
	Broken a{"owned"};
	Broken b = a;  // BP: implicit copy duplicates the pointer, not the buffer.
	std::cout << "shallow: " << b.data << '\n';
	// BP: both destructors delete[] the same address -> double free.
#else
	std::cout << "shallow: skipped (declares a destructor but no copy -> Rule of Three violation)\n";
#endif
}

// Type 2: Rule of Three restores value semantics for an owning raw pointer.
class RuleOfThree {
public:
	explicit RuleOfThree(const char* text) : data_(duplicate(text)) {}
	RuleOfThree(const RuleOfThree& other) : data_(duplicate(other.data_)) {
		// Deep copy: each object owns its own buffer.
	}
	RuleOfThree& operator=(RuleOfThree other) { // Copy-and-swap also handles self-assignment.
		std::swap(data_, other.data_);
		return *this;
	}
	~RuleOfThree() { delete[] data_; }
	const char* get() const { return data_; }
private:
	char* data_;
};

void deep_copy_is_safe() {
	RuleOfThree a{"owned"};
	RuleOfThree b = a;
	b = b; // Self-assignment is harmless with copy-and-swap.
	std::cout << "deep: " << a.get() << " / " << b.get() << '\n';
}

// Type 3: owning a resource through a smart pointer makes the special members correct by default.
class RuleOfZero {
public:
	explicit RuleOfZero(std::string text) : data_(std::move(text)) {}
	const std::string& get() const { return data_; }
private:
	std::string data_; // The member owns the memory; no destructor, copy or assignment needed.
};

void rule_of_zero() {
	RuleOfZero a{"owned"};
	RuleOfZero b = a; // Correct copy generated by the compiler, because members are correct.
	std::cout << "zero: " << b.get() << '\n';
}

int main() {
	shallow_copy_double_free();
	deep_copy_is_safe();
	rule_of_zero();
}
